//export * from './load'
export const LA_LOAD = 'LOAD'
export const LA_REMOVE = 'DELETE'
export const LA_TOKEN = 'found'
export const LA_PAGE = 'page'
export const TIME_ARRAY = 'TIME_ARRAY'
export const TIME_UPDATE = 'UPDATE'
export const TIME_SEC = 'SEC'
export const TIME_MIN = 'MIN'